[package]
authors = ["Thomas McNiven <hello@vevix.net>"]
edition = "2018"
name = "linker"
version = "0.1.0"

[dependencies]
actix-web = "2.0.0-alpha.6"
actix-rt = "1.0.0"
actix-service = "1.0.0"

dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

uuid = { version = "0.8", features = ["v5"] }
seahash = "3.0"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "1.4"
